name: none-shall-pass

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**/*.md'

jobs:
  none-shall-pass:
    runs-on: thevickypedia-default
    steps:
      - uses: actions/checkout@v4
      - uses: thevickypedia/none-shall-pass@v5
