name: update-release-notes

on:
  workflow_dispatch:
    inputs:
      project_version:
        type: string
        description: Version of the project to update release notes for
        required: true
  workflow_call:
    inputs:
      project_version:
        type: string
        description: Version of the project to update release notes for
        required: true

jobs:
  release-notes:
    runs-on:
      - thevickypedia-default
      - posix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Update Release Notes
        uses: thevickypedia/update-release-notes@v2
        with:
          git_token: ${{ secrets.GIT_TOKEN }}
          commit_message: "chore: Update release notes for v${{ inputs.project_version }}"
          filename: release_notes.rst
