name: package-resolver

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**/*.txt"
      - "dev_scripts/*"
      - ".github/workflows/version.yml"

jobs:
  dependencies:
    runs-on: thevickypedia-default
    steps:
      - uses: actions/checkout@v4
      - run: python dev_scripts/dependencies.py
        shell: bash
